### ISSUE TITLE
Android + PayPal 

### ISSUE THREAD

**Issue by jeveloper** [kraffslol/react-native-braintree-xplat#1]
Hi

Thanks for the library

Would this work on android if i wanted to offer paypal payment? or not yet
and is there a reason if it doesn't work

thank you

**Comment by kraffslol** [comment]
Hi! 
The implemented drop-in UI offers the option to pay with PayPal.

**Comment by jeveloper** [comment]
Thank you @kraffslol , appreciate your contribution ! 
Looking to try it with RN 0.28/29
