### ISSUE TITLE
AAPT: No resource identifier found for attribute 'appComponentFactory' in package 'android'

### ISSUE THREAD

**Issue by zasyadev** [kraffslol/react-native-braintree-xplat#108]
I am facing a issue with `react-native-braintree-xplat` . I am getting the following error when trying to build the app.

> \?\E:\projects\deets-mobile-cp\android\app\build\intermediates\manifests\full\release\AndroidManifest.xml:88: AAPT: No resource identifier found for attribute 'appComponentFactory' in package 'android'
> 
> FAILURE: Build failed with an exception.
> 
> What went wrong: Execution failed for task ':app:processReleaseResources'.
> Failed to process resources, see aapt output above for details.

I guess `react-native-braintree-xplat`  is package is causing it because when I remove this package, the app builds successfully. So is there any work around I can use to resolve this error or i'll have to implement the javascript SDK provided by Braintree.

"react": "16.2.0"
"react-native": "0.53.3"
"react-native-braintree-xplat": "^4.0.0"

**Comment by arundas1903** [comment]
I am facing the same issue. react-native-braintree-xplat:processDebugResources

Please let me know if you find the issue again

**Comment by mlazari** [comment]
I have a similar issue after the [update of Braintree SDK to 2.18.1](https://github.com/braintree/braintree_android/releases):
![screen shot 2018-11-08 at 1 05 37 pm](https://user-images.githubusercontent.com/4928274/48195143-79cdf200-e357-11e8-8f1a-8a31acefa93d.png)
If I change the version to 2.18.0 in this file - https://github.com/kraffslol/react-native-braintree-xplat/blob/master/android/build.gradle#L24 - then it builds fine. Does anyone know what can be the cause of that error with 2.18.1?

L.E. I just found a similar issue in Braintree SDK project: https://github.com/braintree/braintree_android/issues/238

**Comment by quinnjn** [comment]
I don't have experience with React Native but the [compileSdkVersion and buildToolsVersion](https://github.com/kraffslol/react-native-braintree-xplat/blob/master/android/build.gradle#L4-L5) on this project is quite behind.

Since [Google Play has added target API restrictions](https://developer.android.com/distribute/best-practices/develop/target-sdk), I'd recommend updating these values soon.

**Comment by zasyadev** [comment]
I found the solution to this problem. 
Braintree has recently updated the library to support Android 28, and the issue comes from there.
You should force `com.braintreepayments.api `to version `2.17.0`

I do it in my project build.gradle with
```
allprojects {
    repositories {
        ......
        configurations.all {
            resolutionStrategy {
                force 'com.braintreepayments.api:braintree:2.18.0'
            }
        }
        ......
    }
```

**Comment by quinnjn** [comment]
@zasyadev that is not the correct answer, it's just a band aid and you're preventing folks from using the latest versions by being stuck on 2.18.0. 

The `compileSdkVersion` for this library needs to be bumped to the latest version and that should solve it. Bumping `compileSdkVersion` would not be a breaking change.

Ian Lake has an [excellent article on picking Android SDK Versions](https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd).
