### ISSUE TITLE
How to upgrade iOS SDK manually?

### ISSUE THREAD

**Issue by anniewey** [kraffslol/react-native-braintree-xplat#127]
As per Braintree email, iOS SDK needs to be upgraded to minimum version 4.10.0. 
Is it just replacing the SDK folder in `react-native-braintree-xplat/ios/RCTBraintree/Braintree`?

**Comment by juergengunz** [comment]
@anniewey how did you end up upgrading to minimum version 4.10.0. ?

**Comment by anniewey** [comment]
@juergengunz I replaced the entire `Braintree` sdk folder with new sdk folder from https://github.com/braintree/braintree_ios/releases/tag/4.10.0 following the [guide](https://github.com/braintree/braintree_ios/blob/master/Docs/Manual%20Integration.md)

I've also verified with BT team on the sdk version of the transaction made which indeed is 4.10.0
