### ISSUE TITLE
PayPal Error on Example

### ISSUE THREAD

**Issue by AdamBrodzinski** [kraffslol/react-native-braintree-xplat#2]
I'm trying to get the PayPal button to work but my own app and the example app are returning the error: `Paypal app switch is missing a returnURLScheme`. However, the CC portion works great.

Digging into what a URL scheme is it seems like that is required for one-touch support and that is enabled by default in the Braintree library. (and I cant seem to disable it, i'd rather not have it for now)

I also tried to follow the instructions on the original repo to add one-touch support but when adding the openURL method to AppDelegate I get the error: `RNBraintree.h not found`. I've tried tinkering with link binaries and can't get it to work.

*any* advice on this would be **very much appreciated**... i'm kind of dead in the water without PayPal support and am spinning my wheels.

There is a similar unanswered issue here:
https://github.com/alanhhwong/react-native-braintree/issues/20

**Comment by kraffslol** [comment]
Hello!
In this repo RNBraintree is now known as RCTBraintree.
So you could try 
```js
#import <RCTBraintree.h>

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  return [[RCTBraintree sharedInstance] application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
}
```
instead and it should work.

**Comment by AdamBrodzinski** [comment]
Ah many thanks! That works 😁 

I also had to add a bit of markup in the plist for iOS9 to be supported:
https://developers.braintreepayments.com/guides/client-sdk/setup/ios/v3#register-a-url-type
 to get rid of this error:

```
 -canOpenURL: failed for URL: "com.venmo.touch.v2://x-callback-url/vzero/auth" - error: "This app is not allowed to query for scheme com.venmo.touch.v2"

```

Not sure if you wanted to add these to the docs? (I can prob. PR later if so)

**Comment by jpuri** [comment]
I am trying to implement change suggested above but `#import <RNBraintree.h>` is failing in appDelegate.h.

Can you plz suggest ?

**Comment by faceyspacey** [comment]
do you need to specify some additional header search paths to make `import <RNBraintree.h>` work? The proposed solution isn't working for me either.

**Comment by kraffslol** [comment]
Hi, Please see my previous comment. It's now <RCTBraintree.h> and not <RNBraintree.h> :-)

**Comment by faceyspacey** [comment]
i meant to paste that. I am doing `RCTBraintree`. I'm assuming I need to add it to my header search paths differently than how `libRCTBraintree.a` is linked. I'm not sure how to reach it's path in the Libraries though??

**Comment by faceyspacey** [comment]
ok, I got it to work by adding `$(SRCROOT)/../node_modules/react-native-braintree-xplat/ios/RCTBraintree` to my header search path recursively.

**Comment by damathryx** [comment]
Hi, I am also getting this error in version 2.4.0. I got no background on iOS and xcode at all where should I put these code?
```
#import <RCTBraintree.h>

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  return [[RCTBraintree sharedInstance] application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
}
```

**Comment by darron-haworth** [comment]
I am with @damathryx , where does this code go?

**Comment by kraffslol** [comment]
Hi! The code goes into AppDelegate.m in the ios directory.

**Comment by darron-haworth** [comment]
There is a [PR](https://github.com/kraffslol/react-native-braintree-xplat/pull/29/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8) pending with steps documenting how to set this up.
