### ISSUE TITLE
getCardNonce is not handling errors

### ISSUE THREAD

**Issue by pspeake87** [kraffslol/react-native-braintree-xplat#20]
using react-native 0.30

`BTClient.getCardNonce("4111111111111111", "10", "20", "400").then(function(nonce) {
  console.log(nonce)
})
.catch(function(err) {
  console.log(err) 
});` 

Im getting a nonce back if I call it with  a valid card but if i call it with a invalid card (for example a 15 digit card) I dont get an error back

**Comment by Wrendered** [comment]
+1

**Comment by the-simian** [comment]
I'm also experiencing this on android in the current build.

**Comment by the-simian** [comment]
https://github.com/kraffslol/react-native-braintree-xplat/pull/23
