### ISSUE TITLE
Remove PayPal Check out bar

### ISSUE THREAD

**Issue by idavidson12** [kraffslol/react-native-braintree-xplat#24]
Using this: 

BTClient.showPaymentViewController(options).then(function(nonce) {
  //payment succeeded, pass nonce to server
})
.catch(function(err) {
  //error handling
});

shows both PayPal and card entry options. I would like to hide the PayPal option. Is there a way to do this?

**Comment by kraffslol** [comment]
Hi! Sorry for the late response. I believe this is controlled by the options you've set on your braintree merchant account (At least on production as far as I know).

**Comment by idavidson12** [comment]
Thank you for your response. In my Braintree sandbox there are no options that would eliminate the PayPay Check out button. But when I click on the PayPal Check out button, I get the popup warning "PayPal app switch is missing a returnURLScheme." I don't find how to edit the PayPal app switch in your directions. BTW, thank you for this module -- it's a lifesaver!

**Comment by damathryx** [comment]
@idavidson12  have you solved this issue?

**Comment by idavidson12** [comment]
Yes I have. It turned out to me a setting on Braintree's side. Thank you.
