### ISSUE TITLE
setup of undefined

### ISSUE THREAD

**Issue by damathryx** [kraffslol/react-native-braintree-xplat#26]
I'm getting this error using BTClient.setup('ezC..') but when I log BTClient its there.
![screen shot 2016-12-17 at 2 11 25 pm](https://cloud.githubusercontent.com/assets/14576761/21284845/d0157716-c462-11e6-9d11-7cc568664f2e.png)

Platform is iOS.
Ver. 2.4.0

i used react-native link for setup. checked the steps manually good but I have noticed this in my build phases under Link Binary
![screen shot 2016-12-17 at 2 14 05 pm](https://cloud.githubusercontent.com/assets/14576761/21284864/46c4f288-c463-11e6-9013-afbdcc8ba1b5.png)
Is this the problem?

**Comment by damathryx** [comment]
I just deleted the libs and added libRCTBraintree.a again then clean and build.

**Comment by bhgames** [comment]
this fixed it for me, too

**Comment by limitsapp** [comment]
this worked for me as well!
