### ISSUE TITLE
Error React/RCTBridgeModule.h file not found in RCTBraintree.h

### ISSUE THREAD

**Issue by ningo-agilityio** [kraffslol/react-native-braintree-xplat#39]
I followed step by step to link **react-native-braintree-xplat** to my project (ios) but I got an error when building (error from file **RCTBraintree.h**) - **'React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>**.
Could you guys point me what's happen with me?

Note: My version React Native is **0.39**.

**Comment by kraffslol** [comment]
Use the 2.4.2 version of the package if you're using React Native under 0.40 and it should work.

**Comment by ningo-asnet** [comment]
You mean I should use package **react-native-braintree-xplat** version **2.4.2**, right?

**Comment by kraffslol** [comment]
Yes, exactly. :-)

**Comment by kmatherne** [comment]
I'm having this same issue using React Native 0.55. I am also using expo kit. Not sure if that is causing the issue.

**Comment by epurban** [comment]
I'm having this issue, did you ever fix it @ningo-agilityio ?
