### ISSUE TITLE
thoughts on including cvv?

### ISSUE THREAD

**Issue by faceyspacey** [kraffslol/react-native-braintree-xplat#4]
I notice the cvv isn't passed along to Braintree, but is accepted by the base Braintree methods in native code. Would a pull request making this change be welcome? I think the ideal case would be that it's optional, correct? 

The goal being Braintree can better detect fraudulent activity when the `verifyCard: true` option is past.

**Comment by kraffslol** [comment]
A pull request for this would definitively be welcome as long as its an optional choice and is supported on both platforms.

**Comment by faceyspacey** [comment]
After looking at how the AVS and CVV rules are configured in the braintree panel and the underlying objective c class, it looks like we should support address info as well:

http://cocoadocs.org/docsets/Braintree/4.5.0/Classes/BTCard.html

https://www.dropbox.com/s/oxkpsz8dcjcxeu9/Screenshot%202016-08-13%2004.45.29.png?dl=0

of course all optionally. I assume all serious ecommerce apps will enable card verification based on collecting this information (which of course the nonce ultimately represents).

**Comment by kraffslol** [comment]
CVV is now implemented thanks to @edvinasbartkus 👍
