### ISSUE TITLE
Upgrade to current braintree version

### ISSUE THREAD

**Issue by bdart** [kraffslol/react-native-braintree-xplat#40]
The current braintree version version used here, still have the bug, that the [`BTAnalyticsMetadata.m`](https://github.com/kraffslol/react-native-braintree-xplat/blob/75036a655bb547d2ae7c440d4904ebfb2fb62f2d/ios/RCTBraintree/Braintree/BraintreeCore/BTAnalyticsMetadata.m#L1) trys to import `BTAnalyticsMetaData.h`. But there is a typo that is fixed in the current braintree release. This typo throws an issue in the newest XCode version `8.3` so that you cannot build to test.

Have you cloned the braintree ios sdk and commited it statically within this repo? Or is there a podfile sneaking around that I am missing out?

**Comment by iancanderson** [comment]
I have a duct-tape fix for the bug that you mentioned here: https://github.com/kraffslol/react-native-braintree-xplat/pull/36
