### ISSUE TITLE
Typo in BTAnalyticsMetadata.m

### ISSUE THREAD

**Issue by nijolas** [kraffslol/react-native-braintree-xplat#44]
Building on iOS throws the following error. The #import statement refers to "BTAnalyticsMetaData.h" when the file is actually "BTAnalyticsMetadata.h". I guess the error message is saying it's not portable across operating systems that are fussy about cases.

Regardless, correcting that reference to a lowercase "d" in the #import statement corrects the issue.

```
/node_modules/react-native-braintree-xplat/ios/RCTBraintree/Braintree/BraintreeCore/BTAnalyticsMetadata.m:1:9: 
error: non-portable path to file '"BTAnalyticsMetadata.h"'; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-path]
#import "BTAnalyticsMetaData.h"
        ^~~~~~~~~~~~~~~~~~~~~~~
        "BTAnalyticsMetadata.h"
1 error generated.
```

New to contributing - I know it's only one line, but I tried to create a PR for this and failed. Do I need to be added to the project or something?

**Comment by nijolas** [comment]
Issue had already been corrected. My apologies

**Comment by ckorhonen** [comment]
Would it be possible to update the version on NPM? I see the fix here on GitHub, but the version installed by NPM/Yarn still appears to be the pre-fixed one. Thanks!
