### ISSUE TITLE
BT not validating card

### ISSUE THREAD

**Issue by arnsa** [kraffslol/react-native-braintree-xplat#46]
Hello,

I've been trying to use this package, but when I am using getCardNonce() function, no matter what data I pass to it (it can be even nulls) it's always returning me a new card nonce. Is it expected behaviour? Shouldn't it return me any error that the card is invalid or something? It's happening on both android and ios. I am using sanbox testing token.

**Comment by edvinasbartkus** [comment]
Maybe this will resolve your issue: https://github.com/kraffslol/react-native-braintree-xplat/pull/47

**Comment by arnsa** [comment]
@edvinasbartkus it did, but only for iOS. It's still not working on Android. :(

**Comment by arnsa** [comment]
Created PR fix for Android: #48

**Comment by kraffslol** [comment]
Should be fixed now with the contributions from @edvinasbartkus and yourself.

**Comment by bhgames** [comment]
I updated to 3.2.0 and this did not cause it to start validating for either platform.
