### ISSUE TITLE
Proceed with Sandbox purchase button does not work.

### ISSUE THREAD

**Issue by malikhijazi** [kraffslol/react-native-braintree-xplat#50]
After calling `BTClient.showPayPalViewController().then(function(nonce) { })` the Proceed with sandbox purchase button does not redirect me anywhere. I am also not getting any errors. Any help will be appreciated.

**Comment by altafan** [comment]
+1

**Comment by xPotion** [comment]
+1

**Comment by matthiasleitner** [comment]
I am also experiencing the same behaviour. The proceed button on the PayPal page links to my apps url scheme but I think the issue is that the page is not loaded in Safari tab but in an In-App view
