### ISSUE TITLE
showPaymentViewController not showing payment method selection options

### ISSUE THREAD

**Issue by tayshuyih** [kraffslol/react-native-braintree-xplat#51]
I have manage to show the drop in payment form using showPaymentViewController and successfully made payment in sandbox. 

However, I am not sure why the "Select Payment Method" dialog is not shown. This library is using drop in UI as in https://developers.braintreepayments.com/start/hello-client/ios/v4 right? I integrated it natively in Android and able to see the "Select Payment Method" dialog correctly. However in react native using this library, the payment UI looks different and there's no "Select Payment Method" dialog. 

Am I missing something here? showPaymentViewController is implemented using drop in UI, BTDropInViewController right? I tried to check in Android version, but cant find how showPaymentViewController is implemented. There is only a "paymentRequest" method there. I can't understand how react native call and show drop in UI here. 

Thanks

**Comment by tayshuyih** [comment]
Ok. I figure out that it's using the older version of drop in UI. Upgraded myself and it's showing up now.

**Comment by dobiedad** [comment]
@darren1982 can you please explain or PR on how you upgraded the version of the UI
