### ISSUE TITLE
Release version with 0.47 compatibility fix

### ISSUE THREAD

**Issue by Andreyco** [kraffslol/react-native-braintree-xplat#65]
Please, release updated version with compatibility [fix for RN 0.47.0](343bd3c8553bb418c0a36deac240dc56e2209a6b) (already in master)
It will surely help people to get started with this package ;)

**Comment by kraffslol** [comment]
Sorry for the delay. Theres now a published version for the fix.

**Comment by Andreyco** [comment]
Thank you :)
