### ISSUE TITLE
address support for AVS verification

### ISSUE THREAD

**Issue by celebvidy-owner** [kraffslol/react-native-braintree-xplat#7]
I see that CVV support was just merged. It seems the last remaining aspect of card verification is being able to optionally collect address info. I'd do it, but i dont have much experience beyond js.

**Comment by kraffslol** [comment]
I could look into it. Do you know which of [these](http://cocoadocs.org/docsets/Braintree/4.5.0/Classes/BTCard.html#properties) fields are required for AVS verification?

**Comment by faceyspacey** [comment]
Here is the Edit AVS rules on the **"Processing page"** of the Braintree webpanel:

https://www.dropbox.com/s/i9dwygmjh1mpkkm/Screenshot%202016-09-26%2019.18.07.png?dl=0

From the looks of it, you might guess that only `postalCode` and `streetAddress` are used, but they provide the parameters for a reason. I think we basically need to support all these parameters (essentially optionally):

```
  postalCode property
  cardholderName property
  streetAddress property
  locality property
  region property
  countryName property
  countryCodeAlpha2 property
```

Any of them can be missing--it's up to the developer to include what they need. 

*"Advanced Credit Card Fraud Tools"* which you need to pay to enable may make use of them. It looks like *"Risk Thresholds"* might make use of them as well. These are additional settings groups on the **"Processing"** page. 

After this, there's only one final missing parameter: `shouldValidate`. If they're added all the same, that option might as well be added too.

**Comment by TSMMark** [comment]
Any word on this? We would like to enable street address AVS.

**Comment by paulducsantos** [comment]
I would also like to turn street address AVS on. any updates?

**Comment by Andreyco** [comment]
Hey guys...
I was in very same situation, when we rely on BT to verify postacl code, ... This feature is missing, I created PR #72, which adds this functionality.
