### ISSUE TITLE
use more unique request code

### ISSUE THREAD

**Issue by AlexSchwabauer** [kraffslol/react-native-braintree-xplat#9]
In **Braintree.java** you define 
`private static final int PAYMENT_REQUEST = 1;`
This will cause issues with other rn-modules that listen to or emitting the same request code, most likely the app will crash.

**Comment by kraffslol** [comment]
Hi!
I'll look into fixing it today.

**Comment by kraffslol** [comment]
Fixed by @kylejones in #19
