### ISSUE TITLE
Thread 1: signal SIGABRT

### ISSUE THREAD

**Issue by Talkwondo** [kraffslol/react-native-braintree-xplat#99]
Hello,
After I called to the funcion:
BTClient.getCardNonce(card).then(function(nonce) {
            //payment succeeded, pass nonce to server
          })
          .catch(function(err) {
            //error handling
          });

I getting this error in the Xcode.

and I don't understand where braintree can know how much the user need to pay? where is that field?

Thanks,

**Comment by paul-apacio** [comment]
Did you discover a solution for this as I am also hitting the same issue.
